install-dependencies-after-pull.sh

* git pull 이후 실행 이후 루트에서 `npm run dev` 실행
* npm 기준 의존성 설치 스크립트 추가
* 명령어 실패할 시 종료

add: git pull 이후 의존성 설치 스크립트(npm)

---

backend/src/routes/offer.routes.ts
frontend/src/components/offer/ModelSelector.tsx
frontend/src/pages/OfferPage.tsx
shared/offer_types.ts
shared/types.ts

제조사, 모델명, 용량에 따른 조건 검색 로직 개발 중

offer page 모델 조건 개발 중

---

.gitignore
frontend/src/components/ManualUpload.tsx
frontend/src/pages/PriceInputPage.tsx

feat: 가격 직접 입력 페이지

---

backend/src/db.ts
backend/src/routes/offer.routes.ts
backend/src/typeorm/addons.entity.ts
backend/src/typeorm/carriers.entity.ts
backend/src/typeorm/comments.entity.ts
backend/src/typeorm/offers.entity.ts
backend/src/typeorm/phoneDevices.entity.ts
backend/src/typeorm/phoneModels.entity.ts
backend/src/typeorm/postCategories.entity.ts
backend/src/typeorm/postFiles.entity.ts
backend/src/typeorm/postImages.entity.ts
backend/src/typeorm/posts.entity.ts
backend/src/typeorm/regions.entity.ts
backend/src/typeorm/reqPlans.entity.ts
backend/src/typeorm/sellers.entity.ts
backend/src/typeorm/stores.entity.ts
frontend/src/components/offer/CarrierSelector.tsx
frontend/src/components/offer/ModelSelector.tsx
frontend/src/components/offer/RegionSelector.tsx
frontend/src/pages/OfferPage.tsx
shared/types.ts

- Offer page 관련 코드 TypeORM으로 마이그레이션
- TypeORM Entity 구조 수정

feat(offer): TypeORM 마이그레이션 및 Entity t수정

---

backend/package-lock.json
backend/package.json
backend/src/db.ts
backend/src/utils/SqlLogger.ts

typeORM 실행 쿼리 로그 가독성 향상을 위해 logger 추가

test: typeORM logger 개선

---

backend/src/routes/offer.routes.ts
frontend/src/pages/OfferPage.tsx

- 검색 결과 리스트 정렬 기능 추가 (기본 정렬 | 가격 낮은 순 | 가격 높은 순)
- 검색하기 버튼 클릭 시, 검색결과 리스트 요소로 스크롤되도록 처리
~~(브랜치 안바꿈 ㅠ)~~

feat: offer page 검색결과 리스트 정렬 기능 & 검색하기 버튼 클릭 시 스크롤 기능 추가

---

backend/package-lock.json
backend/package.json
backend/src/routes/user.route.ts

- 생성된 닉네임이 이미 존재하는 닉네임인지 확인하는 로직 추가

feat: 신규 회원 랜덤 닉네임 중복 확인 로직 개선

---

README.md
backend/src/app.ts
backend/src/routes/priceInput.route.ts
backend/src/routes/store.routes.ts
frontend/src/config/sso-config.ts
frontend/src/pages/LoginPage.tsx
frontend/src/pages/OfferPage.tsx
frontend/src/pages/SignupPage.tsx
shared/types.ts

- 판매자 가입 선택 시 출력되는 매장 선택 UI 추가

feat: 매장(대리점) Input element 추가

---

backend/src/routes/user.route.ts
frontend/package-lock.json
frontend/package.json
frontend/src/components/AddressSearchButton.tsx
frontend/src/components/StoreSearchableSelect.tsx
frontend/src/pages/SignupPage.tsx

- 주소 검색 팝업 추가
- 회원가입 UI 개선
- 판매자 가입 시 sellers 테이블 데이터 insert 처리

feat: 주소 검색 API 기능 개발 & UI 개선 & 판매자 가입 로직 추가

---

backend/src/routes/store.routes.ts
frontend/src/components/store/StoreOfferPriceForm.tsx
frontend/src/pages/StorePage.tsx
shared/offer.types.ts

- Store page: 등록된 시세표가 존재하면 조회 후 출력
- TODO: 추가버튼, 등록된 시세표 없을 시 기본 테이블 데이터 출력, StoreID 가져오기

feat: Store page 시세표 조회 및 출력 개발(ing...)

---

backend/src/routes/admin.routes.ts
backend/src/routes/store.routes.ts
frontend/src/components/admin/StoreDetailModal.tsx
frontend/src/components/store/StoreOfferPriceForm.tsx
frontend/src/pages/AdminPage.tsx
frontend/src/store/authStore.ts

- 관리자 페이지 > '승인 대기 매장' 관리 화면 구현 및 기능 개발

feat: 관리자 페이지 - 승인 대기 매장 처리(승인/거부) 기능 구현

---

backend/src/routes/offer.routes.ts
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/pages/OfferDetailPage.tsx
frontend/src/pages/OfferPage.tsx
shared/offer.types.ts
shared/reqPlan.types.ts
shared/types.ts

feat: OfferDetail page 개발 중

---

backend/src/config/sso-config.ts
backend/src/routes/auth.routes.ts
backend/src/typeorm/socialAccounts.entity.ts
backend/src/typeorm/users.entity.ts
frontend/src/components/Navbar.tsx
frontend/src/pages/MyPage.tsx
frontend/src/pages/OfferPage.tsx
frontend/src/pages/SsoCallbackPage.tsx
frontend/src/store/authStore.ts
shared/user.types.ts

feat: 회원 탈퇴 처리 개발 중..

---

frontend/src/pages/MyPage.tsx

style: 마이페이지 UI 변경

---

backend/.prettierrc
backend/src/routes/auth.routes.ts
backend/src/routes/region.routes.ts
backend/src/routes/store.routes.ts
backend/src/routes/user.route.ts
frontend/.prettierrc
frontend/src/App.tsx
frontend/src/components/CustomCheckbox.tsx
frontend/src/components/Navbar.tsx
frontend/src/components/admin/CarrierModal.tsx
frontend/src/pages/AdminPage.tsx
frontend/src/pages/LoginPage.tsx
frontend/src/pages/OfferPage.tsx
frontend/src/pages/SsoCallbackPage.tsx
frontend/src/pages/StorePage.tsx
frontend/src/store/authStore.ts

- printWidth : 가독성을 위해 디폴트(80)에서 120으로 완화

style: prettierrc 한 줄 허용 길이 제한 완화

---

backend/src/middlewares/auth.middleware.ts
backend/src/routes/auth.routes.ts
backend/src/routes/user.route.ts
frontend/src/components/Navbar.tsx
frontend/src/components/mypage/CommentsModal.tsx
frontend/src/components/mypage/FavoritesModal.tsx
frontend/src/components/mypage/LikesModal.tsx
frontend/src/components/mypage/Modal.tsx
frontend/src/components/mypage/PostsModal.tsx
frontend/src/components/mypage/ProfileEditModal.tsx
frontend/src/components/mypage/SocialModal.tsx
frontend/src/pages/MyPage.tsx
frontend/tailwind.config.js
shared/user.types.ts

- Navbar '마이페이지' > 프로필이미지 & 닉네임으로 변경
- 마이페이지 화면 변경
- [ 마이페이지 > 소셜계정 관리 ] 모달 화면 구현

feat: 마이페이지 UI 개선 & 소셜계정 관리 페이지 구현

---

backend/src/routes/store.routes.ts
backend/src/typeorm/stores.entity.ts
backend/src/typeorm/userFavorites.entity.ts
backend/src/typeorm/users.entity.ts
shared/userFavorite.types.ts

feat: 매장 즐겨찾기 기능 구현

---

frontend/src/components/store/StoreStaffForm.tsx
frontend/src/pages/StorePage.tsx

- [매장 페이지 > 직원 관리] 화면 개발
- 비즈니스 로직 개발 필요

feat: [매장 페이지 > 직원 관리] 화면 개발

---

backend/src/routes/phone.routes.ts
backend/src/routes/store.routes.ts
backend/src/typeorm/sellers.entity.ts
frontend/src/components/store/AddOfferModal.tsx
frontend/src/components/store/StoreOfferPriceForm.tsx
frontend/src/components/store/StoreStaffForm.tsx
shared/reqPlan.types.ts

feat: 시세표 모델 추가 기능 구현

---

backend/src/routes/auth.routes.ts
backend/src/routes/user.route.ts
frontend/src/App.tsx
frontend/src/components/mypage/SocialModal.tsx
frontend/src/pages/LoginPage.tsx
frontend/src/pages/MyPage.tsx
frontend/src/pages/SocialLinkCallbackPage.tsx
frontend/src/pages/SsoCallbackPage.tsx
frontend/src/store/authStore.ts
shared/reqPlan.types.ts

- [ 마이페이지 > 소셜계정 관리 ] : 연결 및 해제 기능 구현
- 로그인 페이지 : 소셜로그인 버튼 클릭 시, 기존에 존재하던 사용자일 경우 '로그인 후 마이페이지에서 소셜계정 연동'하도록 유도
- naver, kakao 개발자 사이트에서 콜백URL 추가
- google, apple 로그인 클릭 시 메시지 출력되도록 처리

feat: SSO 관련 기능 구현 완료

---

backend/src/db.ts
backend/src/middlewares/upload.middleware.ts
backend/src/routes/admin.routes.ts
backend/src/routes/priceInput.route.ts
backend/src/routes/upload.routes.ts
backend/src/typeorm/carriers.entity.ts
backend/src/typeorm/categories.entity.ts
backend/src/typeorm/phoneManufacturers.entity.ts
backend/src/typeorm/phoneStorage.entity.ts
backend/src/typeorm/postFiles.entity.ts
backend/src/typeorm/postImages.entity.ts
backend/src/typeorm/regions.entity.ts
backend/src/typeorm/reqPlans.entity.ts

- USER 에서 SELLER로 변경 시 소속 매장 선태하도록 처리

feat: role 변경 기능 추가

---

backend/src/routes/post.routes.ts
frontend/src/pages/BoardPage.tsx

- 게시글 리스트 출력 디자인 개선
- 인기 게시글 섹션 추가

feat: 게시글 리스트 출력 디자인 개선 & 인기 게시글 섹션 개발

---

backend/src/routes/post.routes.ts
backend/src/typeorm/postCategories.entity.ts
backend/src/typeorm/posts.entity.ts
frontend/src/components/CommunityRecentPosts.tsx
frontend/src/components/RecentOffersList.tsx
frontend/src/pages/MainPage.tsx

- 메인페이지 게시판별 최근 등록된 게시글 출력 섹션 개발 완료

feat: 메인페이지 최근 게시글 섹션 기능 개발 완료

---

backend/src/routes/post.routes.ts
frontend/src/pages/PostPage.tsx

- 게시글 댓글 & 답글 화면 디자인 완료
- 기능 구현도 완료

feat: 댓글 & 답글 작성 및 저장 기능 개발

---

backend/src/routes/post.routes.ts
frontend/src/pages/BoardPage.tsx
frontend/src/pages/PostPage.tsx

- PostPage 댓글 & 답글 좋아요 기능 구현
- BoardPage 페이지네이션 구현 및 반응형 UI 개선

feat: 댓글 좋아요 기능 구현 & BoardPage 게시글 목록 페이지네이션 구현

---

backend/src/routes/post.routes.ts
frontend/src/components/mypage/PostsModal.tsx
frontend/src/pages/BoardPage.tsx
shared/post.types.ts

- [ 마이페이지 > 내가 쓴 글 ] 모달 게시글 리스트 출력 및 클릭 시 페이지 이동 기능 구현

feat: [ 마이페이지> 내가 쓴 글 ] 모달 개발

---

backend/src/routes/post.routes.ts
frontend/src/components/CompactList.tsx
frontend/src/components/Pagination.tsx
frontend/src/components/mypage/CommentsModal.tsx
frontend/src/components/mypage/FavoritesModal.tsx
frontend/src/components/mypage/LikesModal.tsx
frontend/src/components/mypage/Modal.tsx
frontend/src/components/mypage/PostsModal.tsx
frontend/src/components/mypage/ProfileEditModal.tsx
frontend/src/components/mypage/SocialModal.tsx
frontend/src/pages/MyPage.tsx
shared/post.types.ts

- [ 마이페이지 > 댓글 단 글 ] 모달 기능 구현 
- 그리드(리스트) 컴포넌트랑 페이지네이션 컴포넌트화
- Modal 공용 컴포넌트에 icon prop 추가

feat: [ 마이페이지> 댓글 단 글 ] 기능 구현

---

backend/src/routes/admin.routes.ts
backend/src/typeorm/userSuspensions.entity.ts
frontend/src/components/admin/UserDetailModal.tsx
frontend/src/components/admin/UserManagement.tsx
shared/user.types.ts

- [ 관리자페이지 > 회원관리 ] 사용자 목록 출력
- [ 관리자페이지 > 회원관리 > 상세 정보 모달 ] 데이터 출력 및 화면 구현

feat: [ 관리자페이지 > 회원관리 ] 회원 상세 정보 데이터 출력 & 화면 구현
